### ISSUE TITLE
Corrupt cached download is not repaired

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#11]
When attempting to launch this file (SynImgZfDsy20170316A6B), the program crashes with a list of error messages (attached below). Note that even if I download the file manually and put it into the folder where the launcher looks (Arnoldlab->synspy), the program still crashes.

The file is not corrupt (it opens fine if I use synspy-viewer on my own), and it definitely exists on the data management system. Also, there is plenty of room on the hard drive.
![image](https://cloud.githubusercontent.com/assets/28578487/25874630/393401c4-34c8-11e7-9026-05138c87c988.png)

**Comment by karlcz** [comment]
We observed that a failed download left a partial file in the cache and subsequent runs blindly tried to use this cached file rather than downloading again.  Manually removing the bad file from the cache allowed the app to recover.

**Comment by mikedarcy** [comment]
Commit faf712e addresses this by removing any corrupted or partial downloads after the failure condition is caught.  Looking into adding additional cache coherency checks before launch in the case that files get corrupted outside of the application.

**Comment by karlcz** [comment]
@mikedarcy are you planning to do more work on this or should we close it as it is?

**Comment by mikedarcy** [comment]
I'm planning on adding additional checks for coherency before launching.  These changes will likely be folded into the more broadly scoped release of the 2d viewer functionality.

**Comment by BDemps** [comment]
Hi Mike, I know I should start another the for this maybe, but I wonder if
it is all connected. I tried assigning people (including myself) some
nuclei files today and they never went through to be displayed on their
dashboards on the launcher. Is there something I did wrong when assigning
perhaps?

**Comment by karlcz** [comment]
Please create a new issue and provide missing details such as the image region ID.
