### ISSUE TITLE
Issue with Behavioral Data Analysis

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#12]
(1) Zhuowei and I noticed last week that some of the behavior movies are no longer being analyzed by the data management system, specifically having to do with data from FScope 1 (20170125_FScope1). We looked into the metadata for the FScope definitions, and we think that the metadata is correct.

I'm not sure what exactly is going up, but could you potentially update this definition and perhaps re-run the images associated with it?

(2) We have noticed that the movies that we analyze with 20170315_FScope2 look qualitatively different than when we analyze the same movies on the Linux computer. I've attached two images from the same fish movie that was analyzed. "A" was done on the data management system and "B" was done on the Linux computer after moving the movie file over via dropbox.
![a_bhvzfdsy20170505b1 plot](https://cloud.githubusercontent.com/assets/28578487/26069680/a2b0a16a-3956-11e7-9d97-981733b3e9c0.png)
![b_bhvzfdsy20170505b1 plot](https://cloud.githubusercontent.com/assets/28578487/26069692/a99cb612-3956-11e7-8e04-d6a03232ada2.png)

**Comment by karlcz** [comment]
Issue moved to [informatics-isi-edu/fishspy #6](https://github.com/informatics-isi-edu/fishspy/issues/6) via [**ZenHub**](https://www.zenhub.com/)
