### ISSUE TITLE
synspy-registration tool request - Anterior/Posterior Definition

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#13]
Currently, it is a bit difficult to appreciate where we are in the fish when we look at the registered synaptic data. Is there any way to label the axes or somehow label the image such that we know where anterior and dorsal are in the fish? (In the image stacks, dorsal is the top slice and anterior is at the bottom of the images.) This is actually a pretty critical issue for us as we start looking at the synaptic data to see if there are visible (by eye) and reproducible changes in the brain. 

On a "wish list" sort of note, it would be great to get an idea of how far the synapses are from the anterior and dorsal boundaries of the fish (though I know we don't trace that at the moment. Perhaps we could just make a line at where the first slice in the full image is and a line where the frontmost portion of the fish is in the images?).

Happy to talk about this in more detail if it does not make sense.

**Comment by karlcz** [comment]
@BDemps is this still an issue or have you gotten used to the colored axes indicators?

**Comment by BDemps** [comment]
Ah, this is no longer an issue. I figured out the orientation so that it is
no longer painful!
