### ISSUE TITLE
Nuclei Segmentation Assignments Not Functional

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#15]
Whenever I try to assign a file with the "nuclei" segmentation flag, it does not show up on the launcher listing for any classifier user that I've tested it with (including myself, yda, and bsh). These files include, for example, NucImgZfDsy20161202B3D and NucImgZfDsy20161202B6D. Please let me know if there are additional steps that I need to take to make sure that these things actually get pushed over to their task list. Thank you!

**Comment by karlcz** [comment]
I think these are not visible because you have not specified a ZYX Slice yet.
