### ISSUE TITLE
Data Management "Synapse" System Wishlist

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#16]
Hi, happy to discuss these if they don't make sense! Thank you.
**High priority items**:
- ~~New dashboard link: Need a way to see which segmentation results were submitted as "complete" from segmenters. Preferably an area you can click directly from the dashboard~~
-  ~~Need a way to "bounce back" an incomplete file to a segmenter~~
- ~~New dashboard link: dumbed down image data - displays a list containing (1) fish IDs, (2) behavior file added in (y/n), (3) # of image files added in (# of files added for a given fish ID), (4) Standard Length measurement, (5) FScope #, (6) # of image regions added in, (7) # of "Complete" segmented regions, (8) Notes section from the Fish ID. This will be a lighter weight way to see whether we have added in everything for a given fish ID so that we can go back and add things in if they are missing.~~
- ~~Need a way to send a complete file to myself so that I can take a look at what the segmenter has done to make sure they did indeed finish segmenting. I wouldn't be modifying the files - I just like the idea of being able to use the launcher to open an image and automatically load the segments. It takes too long to download things individually otherwise.~~
- ~~Is there a way to interface with (or add to) Mike's launcher program such that we can easily launch synspy-register with segmented nuclei and synapse files? Again, it takes some time to find, download, and then type out everything to load up nuclei and synapse rotations to check on the results!~~

**Lower priority items**:
- ~~Can we modify the data management system somehow to make Karl, Zhuowei, and Bill "superusers" in that we can delete things? Right now, there are a lot of mistakenly added entries that for the most part are just delineated as such by a "DELETE ME KARL" flag in the notes section, but it seems like this will be tedious for Karl in the long run.~~
- ~~Need to display # of slices in a given image somewhere on the page where you look through the "Image" (header) lists of files (not image regions). Note that this will help when we are generating cropboxes for nuclei. We always include the full Z extent in the nuclei segmentation, but currently in order to see the # of slices, we need to download and open the image in e.g., Fiji, which is time consuming and tedious. I think the metadata should say as much so hopefully Synapse can just query that.~~
- ~~In synspy-register, add a couple of reserved keys that allow us to remove tpt1 or tpt2 synapses. (e.g., a toggle such as 'f' to add or remove the **F**irst timepoint and a toggle such as 's' to add or remove the **S**econd timepoint)~~

**Comment by karlcz** [comment]
I've split out items about catalog model/website enhancements to #21.

**Comment by karlcz** [comment]
I've split out items about launcher enhancements as #22

**Comment by karlcz** [comment]
I've split out an item about synspy-register flickerbox controls as #23

**Comment by karlcz** [comment]
I've split off the last item related to catalog access controls as #24 so I'm closing this now empty issue.
