### ISSUE TITLE
Linear brightness display: synspy-register

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#17]
Is there any way to have an alternate mode for synspy-register so that the synapse intensities are displayed (instead of the way they are displayed as binary at the moment)? A proportional linear brightness display would be fine. Anything easy.

**Comment by karlcz** [comment]
I've sent a demo image for review to decide if we want to change to weighted colors.  It's a little awkward with the pointcloud viz utility we have been using in this tool...

**Comment by karlcz** [comment]
Bill likes it so it's committed.
