### ISSUE TITLE
Drag a larger brush or disk to classify puncta en masse in 2d viewer

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/synspy#18]
Users would like to quickly classify multiple adjacent puncta by painting a region coarsely with the mouse. It was suggested that a 5-10 micron diameter disk might be appropriate, and that separate controls to paint positive and negative classification decisions would be useful, i.e. positive via primary/left mouse and negative via secondary/right mouse button drags.  An example use case is to quickly paint over an auto-fluorescing skin region or the halo around a nuclei that otherwise looks like many synapse-scale puncta.

@BDemps

**Comment by BDemps** [comment]
Oops, I just submitted an issue at the same time as receiving this. We were
thinking the same thing!

**Comment by karlcz** [comment]
I've committed an experimental feature to paint multiple segments via mouse drags.

The UX should be self-explanatory once you try dragging with primary and secondary mouse buttons.  A circular region is highlighted in inverted colors beneath the mouse, and all segments in that region get set as either features or non-features depending on which button is held during the drag.

Individual non-dragging clicks still behave as before, but if your mouse is too sensitive it may be difficult to use this feature without accidentally activating the painting mode.

**Comment by karlcz** [comment]
User testing suggested using different radii for the positive and negative paint modes, so it now uses approximately half the radius for the positive mode.
