### ISSUE TITLE
Paintbrush delete

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#19]
Is there a way to delete a wider range of potential puncta in the 2D segmentation program specifically? For example, a sort of "paintbrush" eraser tool that allows you to remove larger groups of points in an individual slice that you can then step through going slice by slice.
I've attached an image that describes why this would be helpful.
(1) Red dashed ellipse: all of the true positive synapses (except for a couple just outside that are unlabeled) are within this ellipsoid region in this section
(2) Blue dashed box: all of these puncta are skin associated (false positives)
(3) Below the white lines: all of these puncta are not within the fish (they are all junk outside; false positives)
(4) The orange arrowheads: all of these puncta are within nuclei (false positives)
(5) The white arrowheads: All of these puncta are too few and far between to be actual synapses (and are also way too dim; false positives)

With the paintbrush tool, we could easily get rid of 2, 3, and 4 false positives, slice by slice much faster than clicking all of the true positives in even this slice. Does this make sense?

The diameter of the paintbrush circle could probably be just bigger than the size of a nucleus, but not much (maybe on the order of 4-6 µm).
![demo_paintdescription_detailed](https://cloud.githubusercontent.com/assets/28578487/26705976/92fa5392-46ee-11e7-9180-938d69687309.png)

**Comment by BDemps** [comment]
(White arrowheads could be later removed by a proximity or intensity threshold?)

**Comment by karlcz** [comment]
Closing this as duplicate with #18.
