### ISSUE TITLE
Launcher enhacements

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/synspy#22]
These are split out from laundry list in #16 

- [x] Reviewer/PI option to toggle different worklist filtering modes
  - Look at tasks for a different user or turn off per-user filtering
  - Look at tasks in a different status or turn off status filtering
  - Possibly toggle which column and direction to sort the task list?
- [x] Way to launch viewer in reviewing mode where any changes will be discarded.  Perhaps just based on task status, so no changes will be uploaded after viewing a "completed" task?
- [x] Way to reverse task status from complete back to in progress if reviewer doesn't like quality of work.
- [x] Runtime option for which viewer to launch (if both are available, e.g. on Linux)
- ~~Launch mode for synspy-register where multiple Image Regions are selected by user and each of their CSV outputs assembled as input arguments~~

Adding support for synspy-register might only be feasible on Linux as bundling that tool is probably too difficult due to the *huge* 3rd party dependency stack for the pointcloud library.

**Comment by mikedarcy** [comment]
Features added in commit 67734030a0586819907e725ef8b3a9aff45d6ec7

**Comment by karlcz** [comment]
This is in release v20170713.6
