### ISSUE TITLE
Flicker-box controls for synspy-register

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/synspy#23]
Some kind of keyboard interface to quickly toggle between composite viewing modes
  - timepoint 1 only
  - timepoint 1 and timepoint 2
  - timepoint 2 only

**Comment by karlcz** [comment]
Need to see how trivial this would be with the current canvas elements

**Comment by BDemps** [comment]
On this note, maybe instead of doing this flicker box, could we just "apply" the rotation transformation to the synspy-viewer somehow so that the rotation states of the synapses in the "segments only" view is in the same exact orientation relative to the transformation that occurred as a result of the rotation matrix? This might be good enough, if the other is too difficult!

**Comment by karlcz** [comment]
There's actually already feature to do that...  you just need to cut
and paste the output line from `synspy-register` that looks like:

   VIEW_ROTATE=1.1000,2.2000,3.3000

and use that as another environment parameter to `synspy-viewer` when
analyzing the *second* timepoint, i.e. the one passed as the second
set of CSV parameters to the registration command.

That printed line is the set of rotations about each axis (in degrees)
as found by the registration algorithm, and it is printed in the
format understood by the viewer program.

**Comment by BDemps** [comment]
What do the rotation matrices mean? Can you do one as an example, showing
both the synspy-viewer and segmented synapses?

On Thu, Jul 6, 2017 at 1:43 PM, Karl Czajkowski <notifications@github.com>
wrote:

> There's actually already feature to do that... you just need to cut
> and paste the output line from `synspy-register` that looks like:
>
> VIEW_ROTATE=1.1000,2.2000,3.3000
>
> and use that as another environment parameter to `synspy-viewer` when
> analyzing the *second* timepoint, i.e. the one passed as the second
> set of CSV parameters to the registration command.
>
> That printed line is the set of rotations about each axis (in degrees)
> as found by the registration algorithm, and it is printed in the
> format understood by the viewer program.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_23-23issuecomment-2D313513722&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=LOGCNNCLnprsadNDaJMUuLzKm4RuYD29E94iyV53ToE&s=LJKxnAHBoFO7j1r5W6hA3judn8B0EPLhQswlNCgBF80&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt-2Dhv-5FQkkhsOJ8xkLQmojDscpjvjgks5sLUbggaJpZM4Nu0Zt&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=LOGCNNCLnprsadNDaJMUuLzKm4RuYD29E94iyV53ToE&s=Z5JUsfVWdmeP3xKrV6roXk5vsGltcEW46PJKCDoblgU&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
Procedure:

1. Run `synspy-register` with timepoint1 and timepoint2 CSV files as normal
   - note the `VIEW_ROTATE=...` line that prints out to console
2. Run `synspy-viewer` on timepoint1 image as normal
3. Run `synspy-viewer` on timepoint2 image adding the `VIEW_ROTATE=...` from step 1.

You should include the `ZYX_SLICE` parameter in both viewer invocations, but only include the `VIEW_ROTATE` parameter in the *second* image.

This parameter is just the angular rotation about the X, Y, and Z axes
in degrees.  The registration command factored that out of the
transformation matrix, discarding the displacement components that
would not be understood by the 3D volume renderer.

**Comment by karlcz** [comment]
The flicker-box controls are now committed (and installed for you to test @BDemps )

Press the keys `1` to `4` on the keyboard to see them toggle the visiblity of their corresponding CSV argument. So,  `1` toggles timepoint 1 nuclei, `2` toggles timepoint 2 nuclei, etc.
