### ISSUE TITLE
Error in loading synapse segments - strange

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#27]
Hi, I get an error that I don't recognize when trying to load the synapses from the ImgZfZdu20161228A6 dataset (see below). One thing that I noticed is that the cropbox definition has a boundary in the X dimension that disagrees with some of the choices of synapses (i.e., some synapses were chosen outside of the cropbox dimension). I'm not sure how this is possible with the launcher program handling everything, but the user who did this data collection did use the software for the before and after images. The before image (A3C) loads synapses fine, while the after (A6C) does not load at all.

Could you look into this, when you have a chance? I'd rather not lose these data, if possible!

![errorfor20161228a6](https://user-images.githubusercontent.com/28578487/27930784-ba322920-624c-11e7-8b5e-c893554d5b2f.png)

**Comment by karlcz** [comment]
Before we chase our tails here...

1. What error message are you seeing that you've never seen before?

2. Is it possible you revised the crop box after the region was assigned?

3. Also, what values specifically are out of range (and by how much)?

**Comment by BDemps** [comment]
(1) "ERROR:Invoking <bound method Canvas.on_key_press of <Canvas (PyQt4) at
0x7f6c11b05990>"

(2) No, i really doubt that I changed it that time. There would have been
no reason too, unless this happened when the FScope died, which I don't
believe it did until January.

(3) The first 75 or so entries when you've sorted the X column.

On Thu, Jul 6, 2017 at 1:37 PM, Karl Czajkowski <notifications@github.com>
wrote:

> Before we chase our tails here...
>
> 1. What error message are you seeing that you've never seen before?
>
> 2. Is it possible you revised the crop box after the region was assigned?
>
> 3. Also, what values specifically are out of range (and by how much)?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_27-23issuecomment-2D313512434&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=Ik1_EUf3EbZ-Dei5Mg3JJK_1QQ4SRU0TAJVM8t6YA_0&s=FN-DyGchR91t25qrxazkkKIHy5bFMJ9UNL6TIzE0GII&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt5hMnqnlxo6AGs4MRR-2DJyzOpzaK7ks5sLUWbgaJpZM4OQIbC&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=Ik1_EUf3EbZ-Dei5Mg3JJK_1QQ4SRU0TAJVM8t6YA_0&s=hdp9yvjLPThWZYQ3WIDtjZARwlY78IWWB15KMqI0zqI&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
is the line before that:

    AssertionError: ('CSV dump does not match image analysis!', './ImgZfZdu20161228A6.synapses.csv')

or something very similar?

**Comment by BDemps** [comment]
Oh, yes

**Comment by karlcz** [comment]
Unfortunately, I don't understand how that existing segments file was
generated and cannot see a way to recover it.  I think you'll just
have to segment the image region over again.

Not only are the out-of-range coordinates odd, but the included "raw
core" and "raw hollow" measurements do not correspond to measurements
obtained when analyzing the source image.  I even tried a larger
slice region that should produce a superset of the measurements 
in any segment file generated from that same image.

If this was one of the first ones performed while testing the new
launcher+viewer integration, we might chalk it up to the bugs we were
hashing through in those first days...?  If this is a recurring
problem, it might indicate a more serious file-handling bug that
scrambled up image or result files.

**Comment by BDemps** [comment]
It's likely that this may have even been the first one that she
segmented... Bummer, because Yasmin is no longer in the lab, so this data
is likely lost, unless the at-home version of the 2D slicer comes online
and we can convinve her to try once more!

On Thu, Jul 6, 2017 at 3:21 PM, Karl Czajkowski <notifications@github.com>
wrote:

> Unfortunately, I don't understand how that existing segments file was
> generated and cannot see a way to recover it. I think you'll just
> have to segment the image region over again.
>
> Not only are the out-of-range coordinates odd, but the included "raw
> core" and "raw hollow" measurements do not correspond to measurements
> obtained when analyzing the source image. I even tried a larger
> slice region that should produce a superset of the measurements
> in any segment file generated from that same image.
>
> If this was one of the first ones performed while testing the new
> launcher+viewer integration, we might chalk it up to the bugs we were
> hashing through in those first days...? If this is a recurring
> problem, it might indicate a more serious file-handling bug that
> scrambled up image or result files.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_27-23issuecomment-2D313535306&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=-fgSXZTu1LH5U9e3SuZIrdNC8Iji-Evz5m5iZRpNLjA&s=LYmo17Tl0pcBQ_5PbO1xXrAF4FK9TQe-5VTd3oJU_GI&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQStyc-5F4v9tHS5f8Wh2dvL8RhxE7RwWks5sLV36gaJpZM4OQIbC&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=-fgSXZTu1LH5U9e3SuZIrdNC8Iji-Evz5m5iZRpNLjA&s=5ZGAmmK8iYcDox3nwOWCXWfLVxRMgcZVg1XAR7US8IY&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818
