### ISSUE TITLE
Mac version of 2d slicer has issues with clicking and with displaying the result of key presses

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#28]
Two potentially interconnected issues have arisen in the mac version of the program:
(1) Usually, when you click a key (e.g., "F" to change the "feature" threshold), the changes that occur in the number associated with that threshold are displayed in the upper left corner of the image briefly. Although the threshold is indeed updated (you can see an increase or decrease in the number of clickable segments, depending on whether F is capitalized or not), the screen does not display the threshold value in the upper left corner.
(2) When you click to update a segment to a false or true positive, the click actually occurs very far away from where the mouse pointer is located. See attached image to get a general idea of how far away the click is located. The red arrow refers to approximately where the mouse pointer is located, and the "flashlight" circle indicates where the click is actually registered on the image.
<img width="1440" alt="arrowbug" src="https://user-images.githubusercontent.com/28578487/28578322-440f2998-710e-11e7-8228-ba8ccdb43ed5.png">

**Comment by karlcz** [comment]
This seems to be a portability issue related to the high-dpi "retina" display feature on Macs.  A fix is in progress...

**Comment by mikedarcy** [comment]
Fix added to release: https://github.com/informatics-isi-edu/synspy/releases/tag/v20170713.7

**Comment by BDemps** [comment]
Great, this works perfectly. Thank you for the fix!!

The only thing that seems to be missing now is that when I hover over
something that should be clickable, I no longer see a change in color to
indicate that I'm hovering over something clickable. It makes it a lot
easier to know whether what you are clicking is a possible segment or not.

On Wed, Jul 26, 2017 at 12:59 PM, mikedarcy <notifications@github.com>
wrote:

> Fix added to release: https://github.com/informatics-isi-edu/synspy/
> releases/tag/v20170713.7
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_releases_tag_v20170713.7&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=675umhW38F5Om6s5OWBFKGEXAovYI1SABXvV6J8qcO8&s=ayGp0esOo9f76WtnPdRxbS4QlYbIzAIefytw3smY9kI&e=>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_28-23issuecomment-2D318165331&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=675umhW38F5Om6s5OWBFKGEXAovYI1SABXvV6J8qcO8&s=zFS9MjhqU5SeYllZEBG02v1k1dlkQvabULgzEsiDT9M&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt1a-2DJTFuJvt8lLBITYUIvSrXqBvcks5sR5q7gaJpZM4OirAY&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=675umhW38F5Om6s5OWBFKGEXAovYI1SABXvV6J8qcO8&s=yIjeDjOBRNRkKdfXytzFND299LSr8hkNYy5GW_BSL4M&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by mikedarcy** [comment]
Is this only on Mac? Or do you see it on Windows as well?

**Comment by BDemps** [comment]
I gotta get someone to try it on windows. I'll get back to you as soon as I
can. Hopefully within 15

On Thu, Jul 27, 2017 at 1:13 PM, mikedarcy <notifications@github.com> wrote:

> Is this only on Mac? Or do you see it on Windows as well?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_28-23issuecomment-2D318473495&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=llqoLTmwmWMqEGhpoPVLkHXkohhaSHfOkgfM2nWXlPc&s=N6U3kutisbVJT3hBw-rYI4cQf7JVm-bA-AAfi-csW_k&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt6HoaC-2DFXak-5FH5AlpDw-5FlBPkMHUZks5sSO-2DFgaJpZM4OirAY&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=llqoLTmwmWMqEGhpoPVLkHXkohhaSHfOkgfM2nWXlPc&s=IZ99LFXQjmf62yb3gaaDy3PluUJg3BKQjadl79Q2LOQ&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by BDemps** [comment]
Okay it is definitely also an issue on Windows.

Another bug I found on windows (that maybe I mentioned before) is that the
nuclei view thresholding seems odd - seems like they make synapse like
segments instead of nuclei like segments. I'm not sure what is happening :(

**Comment by karlcz** [comment]
You mean you see a small spot turning yellow with the threshold
adjustment?  If so, try scrolling up or down through the Z stack and
see if it gets larger...  You'll get a small section if your Z slice
falls towards the top or bottom of the ellipsoid region.

**Comment by karlcz** [comment]
The bug described in this issue was fixed.  If there is a different problem, please open an issue specifically for it.
