### ISSUE TITLE
Data management system changes can cause synspy-launcher to crash

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#34]
I was updating some files on the Synapse data management system today (removing failed "Status" region data) and after saving something that also showed up in my list of "things to do" in the synapse launcher, the synapse launcher itself crashed. It loaded right back up again, so I doubt this is a huge issue, but I thought it was worth mentioning in case this is the tip of an iceberg of a bigger problem...

**Comment by karlcz** [comment]
This sounds like the launcher may be making some unsafe assumptions about the state of the catalog. We should cope with records matching or no longer matching our filtering criteria each time we query the catalog, since there may be asynchronous changes.

**Comment by BDemps** [comment]
Is this because we are now allowed to delete things and the software holds
on to some form of a record that is gone or something?

On Fri, Sep 1, 2017 at 12:12 PM, Karl Czajkowski <notifications@github.com>
wrote:

> This sounds like the launcher may be making some unsafe assumptions about
> the state of the catalog. We should cope with records matching or no longer
> matching our filtering criteria each time we query the catalog, since there
> may be asynchronous changes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_34-23issuecomment-2D326661980&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=p991IqE9qxRS7y8p0_bJdH9DIk8nYWimya_k3dZVzqk&s=XeBuqjSziZF3OA-rhdi3UplxBTago365hBhcfOvWguU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt6I8-5F4Cb-5FzxhK1nxldwpnYqoXLyvks5seFcPgaJpZM4O9rDr&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=p991IqE9qxRS7y8p0_bJdH9DIk8nYWimya_k3dZVzqk&s=y08B65OGPx9AaKGfyujkmqZCAYHaiHRNiVm4dKw34kY&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
@BDemps  I've assigned it to @mikedarcy to take a look.  There isn't anything you are doing "wrong". The launcher must be making some fragile assumption about consistency of catalog query results over time and getting confused when the external edits cause them to change state unexpectedly.

The "status" field serves a prominent role in the launcher queries as well as other server-side task automation, so it is not too surprising that this would cause confusion if you've started messing with "status" in ways that were not encountered before.

Note, I think this is a lower priority issue since you can mostly avoid the issue by not editing via the website while you are using the launcher.  Let us know if this assumption is wrong.

**Comment by BDemps** [comment]
Yes, don't bother fixing. Just wanted you to be aware in case you thought
it was a symptom of a larger problem

**Comment by mikedarcy** [comment]
I've added an extra layer of error handling to help narrow this (and other potential crash errors) down.  Now, when a unhandled runtime error occurs, a message box will pop up and alert you.  On the message box, there will be a "Show Details" button.  Click the button to expand the details, and copy the text displayed and paste it into the issue tracker.

**Comment by BDemps** [comment]
I haven't seen this in a long time, so I feel like it is fixed? You guys can close, if you'd like!
