### ISSUE TITLE
"Viewer subprocess Execution Failed" Error for Synspy

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#36]
An interesting error occurred on the Linux computer, preventing one user (Kwa) from performing segmentation. SynImgZfDsy20170505A3C brings up an error ("viewer subprocess execution failed") when synspy tries to run it. Here's the catch - the issue ONLY occurs when you do 3D view mode. On 2D slicer mode on either Linux or Mac computers, the image seems to open fine.

Any idea what could be the problem?

**Comment by karlcz** [comment]
The easiest way to debug this would be to manually launch `synspy-viewer` on the spim image file giving the proper crop box as a runtime parameter.  Then the crash should show more diagnostics in the terminal.

It might be worth testing against a freshly downloaded copy of the image file as well as the one in the launcher's download cache folder.  The 2D viewer uses a completely different file (the pre-processed NPZ), so if there was a problem downloading or storing the spim image, it would only affect the 3D viewer.

**Comment by karlcz** [comment]
@BDemps  I'm not sure if you saw that I responded here and co-assigned you, so I thought I'd ping you explicitly...

**Comment by BDemps** [comment]
Yup, I saw. Was gonna do this this afternoon! Thanks for the reminder though

**Comment by karlcz** [comment]
I tested `SynImgZfDsy20170505A3C` with the 3D viewer both via manual download and via the launcher and it worked both times.  So, I am pretty sure you must have had a botched download and your download cache is corrupt.

So, please try clearing it out and re-testing. If it still fails, run synspy-viewer manually on the file with the correct XYZ_SLICE parameter and provide the console outputs from the crash.

**Comment by BDemps** [comment]
So, I tested it and still had issues. Here's how I resolved that one (very
strange):

I downloaded the file and opened it in Fiji. It had incorrect ZYX voxel
sizes. I changed them to the correct voxel size and then saved as a
different file name as .ome.tiff in Fiji. Then, I opened that file, it had
correct numbers but incorrect scale (it had four orders of magnitude off of
what it should be for some reason). I changed it back to the correct scale
again and then just clicked save (instead of save as). Then, I used
bfconvert to change it to a different filename with .ome.tiff. Then, I was
able to open it with synspy-launcher!

I think the student will need to re-check this one, as I don't think it was
ever properly opening before. In fact, I'm not sure how she was able to
segment it at all. Maybe she started before the cache got corrupt? Anyway,
it is an odd solution but maybe it will be the case for some number of
images in the future. At least we have a fix...

On Wed, Sep 6, 2017 at 2:54 PM, Karl Czajkowski <notifications@github.com>
wrote:

> I tested SynImgZfDsy20170505A3C with the 3D viewer both via manual
> download and via the launcher and it worked both times. So, I am pretty
> sure you must have had a botched download and your download cache is
> corrupt.
>
> So, please try clearing it out and re-testing. If it still fails, run
> synspy-viewer manually on the file with the correct XYZ_SLICE parameter and
> provide the console outputs from the crash.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_36-23issuecomment-2D327615611&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=jFQ3llPAnHV-Zi_y2PPd9DUdIyrJ-JsIx9GmQxaCdPk&s=AFEqJtRf06uGgTjhpSDpXqzlMc0LO8QjeDyoDadcTbY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQStxwHiRsCF4xFUHg0qm4K0hDsdVzzks5sfwxkgaJpZM4PGbQT&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=jFQ3llPAnHV-Zi_y2PPd9DUdIyrJ-JsIx9GmQxaCdPk&s=gx8vBTSMLqQvw6fXRUR2GY_L3RsJs-DtcBD8VFPlY5o&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818
