### ISSUE TITLE
Error "no space left on device" during region pre-processing

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#40]
There's a weird error in status on NucImgZfDsy20170907A6B
"failed: [Errno 28] No space left on device"

**Comment by BDemps** [comment]
I tried deleting the other new nuclei ones to see if the synapse ones at least get generated, but no luck so far :(

**Comment by karlcz** [comment]
So to be clear this isn't a problem creating regions.  It is a problem with the automated processing to generate the NPZ file on the region.

**Comment by karlcz** [comment]
I think it's running out of disk space in the temporary area where it processes images.  I'm not sure if there are any other storage leaks, but I notice you are making substantially larger images (deeper Z stacks) so it might just be hitting a limit that was sufficient for the smaller images...

**Comment by karlcz** [comment]
When things like this happen, don't delete the failed region.  At most, clear the failed "Status" field on one item at a time to see if it will succeed on the next attempt...

**Comment by karlcz** [comment]
A fix for this is in the release candidate under test on the staging server.  It avoids copying the whole image into the temporary work area and also increases the temporary work space so that computed results won't hit a limit as easily either.

**Comment by karlcz** [comment]
This fix is in production and we've seen one of the larger images process successfully.
