### ISSUE TITLE
Skip pre-processing for nucleic regions

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/synspy#41]
In practice, users are classifying nuclei using the 3D viewer which uses the raw SPIM image as input, not the pre-processed NPZ needed for the 2D viewer.

To save disk space and reduce processing delays, we should skip production of NPZ for nucleic regions. These are slower and larger because the region of interest is usually substantially larger (nearly full-frame) compared to the synaptic regions.

**Comment by karlcz** [comment]
@mikedarcy  can you confirm that the launcher does not depend on the NPZ file URL column when configured to use the 3D viewer?

**Comment by mikedarcy** [comment]
Confirmed. 3D mode only depends on the "URL" field and ignores "NPZ URL".
