### ISSUE TITLE
Launcher needs to allow recovery from network errors

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#42]
Summary:

It seems that under some circumstances, the user can lose work if there is a network outage when they exit the viewer and the launcher attempts to upload the results of the work session  but fails.

- The launcher needs to catch any errors and return to some kind of error dialog which will allow the user to manually initiate a retry, potentially after intervening to restore network connectivity.
- The user's login session may have expired after a prolonged outage, so the viewer needs to also allow re-authnentication as part of the recovery and retry sequence.
- We do not expect to address recovery if the user kills the launcher before successfully uploading the work session results. In this case, the work state will still be lost.

Original issue text:

When users click "shift D" it just displays parameters like gain and thresholds without actually dumping the data. "Save Progress" still works, but it would be good for them to be able to save periodically with a dump in case the internet cuts off unexpectedly, severing the tether to the data management server, which is apparently crippling.

**Comment by karlcz** [comment]
The current viewers know nothing about the remote server, and the launcher handles download and upload only at the beginning and end, respectively, of one viewer launch cycle.  Therefore, it's not really feasible to save incremental progress to the server via the `D` command in the viewer.

The `D` command does save to the local work area on the client machine, but this only helps in the case that you experience a viewer crash such that the normal save at the end fails.  In any case, the launcher can only upload the saved results after it detects that the launched viewer has exited.

I don't think we have enough resources to complicate this launcher/viewer combo with an offline worker mode. But, I think we should fix it if it is losing data.  Can you confirm that the launcher actually lost data?

If the network is lost during the launcher upload sequence, I think it should report an error and stick around with a similar dialog to the one that happens after the viewer exits, and let the user try to "save progress" or "complete" the item again with another button press, after they've restored network connectivity.

@mikedarcy

**Comment by BDemps** [comment]
I see, okay yes we definitely don't need a dump command then. I'll just
tell the segmenters to quit periodically to save changes.

Note that yes, one of the segmenters did actually lose data because he
closed his Computer lid (knocking it offline) and then when he opened it
back up it allowed him to keep clicking and segmenting but then after he
clicked the "x", no data was saved from what he did!

**Comment by karlcz** [comment]
I've revised the issue title and description with what I understand to the be the problem, and we'll try to keep it in mind when we have a chance to revisit the launcher code.

In the short term, the workaround is that the user be cognizant of the need for an active internet connection and finish any work session before they suspend their laptop or walk away from the network...

**Comment by BDemps** [comment]
Yes, that should be good enough - user must be cognizant of their work.

**Comment by BDemps** [comment]
I feel like we can close this one now. The segmenters have been doing save changes more regularly and it no longer seems to be an issue.
