### ISSUE TITLE
Track review status in launcher curator mode

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/synspy#44]
To streamline the work flow, curators would like to be able to toggle and see a "reviewed" status in the curator mode of the launcher.

- [x] A new boolean state for each region. Add a column "Accepted?" also visible from the web GUI.
- [ ] A context menu action to toggle the boolean state from the launcher task list.
- [x] A visual indication of the state within the task list.
- [x] Sorting on the new column should allow quick identification of unreviewed items, but the curator can still sort on other columns and see reviewed and unreviewed items mixed together.

The curators do not want the reviewed items to disappear, as they sometimes still want to open them up and view the data again.

@BDemps

**Comment by karlcz** [comment]
I'm going to define the column as "Accepted?" in the next dev system release, with the expectation that it normally starts `null` and items failing review will be marked incomplete to allow the grader to improve their work until review finally marks it as `true` to accept the quality.  But, if the curator really wants to reject the work permanently, they could set it `false`.

**Comment by BDemps** [comment]
Oh that's perfect!!

**Comment by karlcz** [comment]
@mikedarcy  I've added the "Accepted?" column to "Image Region" on the dev server and exposed it via Chaise so we can play around with that whenever we have time...

**Comment by karlcz** [comment]
I've added the "Accepted?" column to the launcher work list as a read-only and sortable column. There is no support to toggle its state from within the curator mode yet.

**Comment by BDemps** [comment]
Should we make a mac and windows version of the new updated synspy-launcher soon? It would be great to be able to assign due dates, if possible!

**Comment by karlcz** [comment]
I don't remember... is Due Date exposed on your up to date Linux launcher yet?  I.e. is it just a matter of rebuilding the launcher bundles, or you still need a feature enhancement first?

**Comment by BDemps** [comment]
It is indeed on the Linux launcher. That version is done on the "synapse"
github website, but there's no link to Mac & PC yet. I think we're done
with enhancements for now.

I think the only thing that is not necessarily great is the click and hold
for painting. It seems like the mouse is pretty sensitive on the linux
machine, so it goes to paint really easily. Didn't we decide we would make
paint version go only if you hit a hotkey?

On Fri, Jan 12, 2018 at 1:54 PM, Karl Czajkowski <notifications@github.com>
wrote:

> I don't remember... is Due Date exposed on your up to date Linux launcher
> yet? I.e. is it just a matter of rebuilding the launcher bundles, or you
> still need a feature enhancement first?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_44-23issuecomment-2D357364996&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=YkQyV6iRKOcYvBkxf9dHLAV-U7B-5vuhPU-5x7DqDts&s=_YHnULgWvUkomoVTp5gRMW200TJBNHORRdFSd9-OJuA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt1YTbuqCEeAIhIPuKEB4L2rf7P7fks5tJ9SGgaJpZM4PpARF&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=YkQyV6iRKOcYvBkxf9dHLAV-U7B-5vuhPU-5x7DqDts&s=F_UnzMRlQZ_w6HevJftphV8XepxmTBVsH4FM-8JBo9s&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
@BDemps  do you still need an enhancement of the launcher GUI to manage due dates as per this original issue description?  Or is the current ability to set them via the web browser good enough, in which case I will close this old issue?

**Comment by BDemps** [comment]
It's fine in the web browser. Go ahead and close. Thank you!

Quick question - can non curator people see the due dates in the browser?

On Mon, Feb 12, 2018 at 5:05 PM, Karl Czajkowski <notifications@github.com>
wrote:

> @BDemps
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bdemps&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=iEIFXb3hKOgFQOeMnMgKDbcgPSuVE0qvnA8VCbEhMKY&s=LixyvuCFLeZuPxExvF4XQuyfY_xupSndVNLxwtlHLYI&e=>
> do you still need an enhancement of the launcher GUI to manage due dates as
> per this original issue description? Or is the current ability to set them
> via the web browser good enough, in which case I will close this old issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_44-23issuecomment-2D365116781&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=iEIFXb3hKOgFQOeMnMgKDbcgPSuVE0qvnA8VCbEhMKY&s=SMTqbfeu6Qx_ekZF4aBk4Y1sf8aKOPhCDElaBAVOMv4&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt3ni6qKwUN0pXlZuxa0FTEBB87Zxks5tUN-5FkgaJpZM4PpARF&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=iEIFXb3hKOgFQOeMnMgKDbcgPSuVE0qvnA8VCbEhMKY&s=DU3a1d5Fzon6j3bWEx1ofhAkRLvg-20CeOibJfJQbaM&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
At present, everyone allowed into the website sees the same content in the browser for read-only scenarios. They are only restricted in their ability to edit.

**Comment by karlcz** [comment]
Closing this issue. Please use other channels for further discussion unrelated to the original issue description.
