### ISSUE TITLE
Add and expose more notes

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/synspy#47]
We should allow entry and display of notes in more places in the model

- ~~Regions~~
- ~~Image Pairs~~
- Synaptic Pairs

See #51  for this: ~~It would also help to denormalize notes from related entities in more presentations. Easy fixes should be considered first, without doing invasive model changes if an easy fix is not apparent.  It may be better to wait for new front-end features than to do too much temporary work here.~~

**Comment by BDemps** [comment]
Hi, the notes that would be great to expose on the Image Pairs and Synaptic Pairs would be:
(1) Std. Len
(2) "Steps" used (or somehow show whether it is a control or experimental condition, which is really only visible by looking at the "description" of a particular "protocol" definition
(3) Issue Date
(4) A unique notes section that allows analytical data from Greg/Andrey/Sanjay analysis to be put in directly. e.g., I could put in the number for KL divergence for each
(5) # of segments in pre/post that were segmented

**Comment by BDemps** [comment]
Note: notes are only really interesting for synaptic pairs, not so much for image pairs

**Comment by BDemps** [comment]
Also, an "ask" from Don, that would be interesting to see, if it is easy enough to implement:
On the same page, below where the synapse pairs are located, could we add a histogram of intensity values for the synapses in each image? They can be on separate graphs, but they should at least be on the same scale and shouldn't be normalized.

Or, in the worst case, at least a report of the integrated intensity of all synapses before and after. (This will be a decent indication of whether something bleached or had a crazy loss without even really going into the data itself, do you agree?)

**Comment by karlcz** [comment]
So this original issue boils down to just adding a text Notes field to Synaptic Pair Study records.  The other comments are not about a new Notes field, but rather to also show subject and image info when presenting a study pair record.

**Comment by karlcz** [comment]
A notes field and data-entry is in the dev system to test along with other updates for a future release.
