### ISSUE TITLE
Shifted data sets

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#50]
There are two interesting datasets on the management system that seem to have well aligned nuclei but pretty clearly translated sets of synapses. Do you think there could be something wrong with the rotation? I'll try resegmenting the nuclei on the first one, but I feel like even though there are some nuclei pair errors, it wouldn't be THAT big of a change.

Most apparent with definite shift: **SynStd6475**

Not sure if this is a shift or if this is a true change in the data (much less apparent, but if it is a real change and not just a translation/rotation error it is hugely dramatic in this learner!): **SynStd6061**

**Comment by karlcz** [comment]
This study was re-registered today.  Do you still have a question about it?

**Comment by karlcz** [comment]
To me, it looks consistent with the interactive registration tool that can flag the paired points and show nuclei and synapses simultaneously...

**Comment by karlcz** [comment]
I think we can safely say that this is actual distortion in the images and not an alignment artifact.
