### ISSUE TITLE
Requests from users for 2D viewer enhancements

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#53]
Viewer2D tasks boiled out of original issue:

- [x] Show total number of slices in heads-up display along with slice position
- [x] Drop the "non-synapse" classification state and just toggle between "synapse" and unclassified
- [x] Add some control to step through several brush radii for paint mode
- [x] Add some kind of sticky paint mode to avoid having to drag?

## Original text of issue

Could the following be implemented in the 2D slicer mode of synspy-viewer (the one that people use on their laptops)? Note that if anything is too difficult or you think it is not a good idea, let me know.
(1) Can you enable 1-click (instead of 2-clicks) for selecting "true positive" segments out in the 2D slicer mode. 
   --> The 2D slicer program doesn't seem to have the same issue as the 3D slicer mode where clicking once and then hovering over a nearby spot results in it being selected (probably due to the fact that you don't have the option to rotate the data).  This will speed up segmentation significantly.
(2) Can you display the total number of slices in a particular image when it is opened up, along with the other data that is displayed?
  --> A number of segmenters will actually spend the ~2min or so that it takes to scroll through the data just to see the total number of possible segments before they go ahead and segment at all, which is a huge time waster!
(3) Can we improve the paintbrush mode in one of the following ways:
   (a) Can you potentially add an on/off hotkey toggle button for painbrush mode such that when it is on, it is  always painting true positives?
   (b) Can you add a hotkey toggle button that changes the size of the paintbrush in 2-3 different sized circles?
   (c) Can you enable a hotkey toggle for "continuous click" mode? This means that any segment that you hover over while in this mode will be automatically be switched to "true positive" until the mode is toggled off.
  --> Basically, the paintbrush mode as it stands is a bit of a time waster because you have to wait a fraction of a second after every click in order to start it going, each time you click. That time adds up. Also, the "continuous click" mode would cut down on the amount of time needed to actually click, which could be a large time saver.

**Comment by karlcz** [comment]
The reason it is 2 clicks is that it currently cycles through the following order of states:

1. The segment is not classified (initial state)
2. The segment is classified as "non-synapse" (after 1st click)
3. The segment is classified as "synapse" (after 2nd click)
4. Go back to not classified (after 3rd click)

So, you now want to swap the sequence order so that the 1st click classifies it as "synapse" and the 2nd click classifies it as "non-synapse"?  Or do you want to get rid of the explicit "non-synapse" class entirely, and just toggle between "synapse" and "not classified"?

**Comment by BDemps** [comment]
I would say to get rid of the "non-synapse" class entirely. But again, only
for the 2D slicer version. It is still critical in the 3D viewer version,
since there is a time lag between click and selection.

  Since we no longer have an explicit "endorse" or "expunge" button on the
2D slicer, I think the "non-synapse" class is kind of unnecessary. When we
could remove them at will, they might have been useful with the paintbrush,
but now that they're just there, it's an added time sink that the
segmenters would waste too much time really worrying about. What do you
think? Does this make sense?

On Wed, Nov 29, 2017 at 11:50 AM, Karl Czajkowski <notifications@github.com>
wrote:

> The reason it is 2 clicks is that it currently cycles through the
> following order of states:
>
>    1. The segment is not classified (initial state)
>    2. The segment is classified as "non-synapse" (after 1st click)
>    3. The segment is classified as "synapse" (after 2nd click)
>    4. Go back to not classified (after 3rd click)
>
> So, you now want to swap the sequence order so that the 1st click
> classifies it as "synapse" and the 2nd click classifies it as
> "non-synapse"? Or do you want to get rid of the explicit "non-synapse"
> class entirely, and just toggle between "synapse" and "not classified"?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_53-23issuecomment-2D347975656&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=jKTnk-hvJtSs8nuMAAI6szqbs8laFiOUzCcLi_gUbFY&s=W2AwR40tLIaJYHq_KrKzLVwV-3dmCxMGOeFt2NLeEGo&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQStzGVGgy03h9Pt07C80yqXjbZye-2DRks5s7bVqgaJpZM4QlD73&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=jKTnk-hvJtSs8nuMAAI6szqbs8laFiOUzCcLi_gUbFY&s=WesdnbhLkuaamN23iRJjQCIcNeVzkZyp_pkGw1MzBho&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
I am wondering, why do you need a sticky paint mode?  Is dragging difficult on some machines?

It is intended that users drag the paintbrush around and paint continuous regions, not that they move around and click.  I just want to make sure we're addressing a real usability problem and not a training problem...

Also, if we can add several brush radii, then this would avoid the need for the other hovering mode, wouldn't it?  I mean, that's just painting with a smaller brush.  I think all the other paint-mode features are still relevant, e.g. showing a disk for the effective target area and painting whatever falls beneath it.

**Comment by BDemps** [comment]
Some folks paint with trackpad on their laptops. It's tough to click and
drag with a trackpad

**Comment by karlcz** [comment]
@BDemps  I've got code changes for these enhancements to viewer2d.  Let me know when you'd like them installed to the lab machine for you to test.  After that, we can worry about getting an updated build for Mac/Win.

- The app now just toggles between "true synapse" and "unclassified" states
- The Z position is reported like  "5 of 193" on screen
- The Left/Right arrow keys adjust a paint brush zoom factor to shrink or grow in small increments
- The P/p keys enable or disable sticky painting mode
- The E/e keys enable or disable sticky erase mode

**Comment by BDemps** [comment]
Yes! I can test it today if you apply. Go for it. I'm just doing nuclei
segmentation for registering while i wait for the fish to be ready for spim

**Comment by karlcz** [comment]
It should be updated on the workstation now.

**Comment by BDemps** [comment]
So, I tested this, and it works really well, except for one small detail.
Did you intend for it to now require a double-click to change the state of
a particular segment, or is that a strange side effect of the change you
made between toggling from true to unclassified synapses? I think a single
click would be okay. Other than that, I think this is exactly what the
users hoped for. Thank you!

On Fri, Dec 1, 2017 at 2:10 PM, Karl Czajkowski <notifications@github.com>
wrote:

> It should be updated on the workstation now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_53-23issuecomment-2D348627807&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=CuVmRndamLbuzLb8Gm0ZnT5xBXipESnY0yYs6eX3iH8&s=OHf00yPQHyWkvsYm_tiWj97HnKgd2ns3UopvFozJHvA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQStyRo-2D1wc9Mby5edtTJs8YanacaYCks5s8HltgaJpZM4QlD73&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=CuVmRndamLbuzLb8Gm0ZnT5xBXipESnY0yYs6eX3iH8&s=ZHPbCtlQVLB0JGAzJoaUIQrfY2MnPVPHHQ0pUmz5gqE&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by BDemps** [comment]
Oh, a user just discovered an interesting and very significant bug. Apparently, no matter what the N or F threshold is set to, EVERY possible synapse is painted when you are moving around the paintbrush in sticky mode (also in not sticky mode, too!).

**Comment by BDemps** [comment]
Apparently, this is also the case on the laptop version with the non-sticky painting. How strange that we didnt notice till now. We've always been minimizing the thresholds, I guess!

**Comment by karlcz** [comment]
That paint behavior was already there so unrelated to this issue. I opened #57 for that.

The simple clicking behavior seems like a bug introduced with the sticky paint feature. Definitely not intended.

**Comment by karlcz** [comment]
The fixes for this were pushed and user-tested.
