### ISSUE TITLE
Displaying "Due date" on synspy-launcher GUI

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#54]
- [x] Add a Due Date column to Image Region table and GUI config
- [x] Expose the Due Date in the launcher

Is there a way we could add a column where I input a "due date" into each of the assigned datasets in curator mode? It would help segmenters see which are the most relevant datasets that they should be working on and will hopefully give them more of an impetus to finish in a more timely fashion.

**Comment by karlcz** [comment]
The Due Date column is enabled on the dev server to demonstrate date-entry, display, and search.

**Comment by karlcz** [comment]
@mikedarcy   this is another small launcher change we should try to get to soon and try to roll up with #44

**Comment by karlcz** [comment]
I've added this to the launcher code as a read-only and sortable column display.
