### ISSUE TITLE
Revoking assignments

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#55]
This may open a can of worms (and it may be fixed based on the "already viewed" suggestion being implemented), based on the state of the data management system. Right now, there are a lot of assigned datasets that will never be segmented, and some that I assigned to more than one person but only want one person to work on for now. Is there any way to "remove" an assignment to someone either permanently (deleting the entry from the data management system, which I know might cause problems), or temporarily so that it does not show up on their list or the data management system list (e.g., calling it "null" or "sidelined")? It would help curators see the datasets that are being actively segmented more easily for keeping track of people as they go, especially since undergrads (for example) cycle through the lab on a somewhat regular basis...

**Comment by karlcz** [comment]
I think you should be able to edit the Image Region records and clear the assignee entry already. Have you tried that?  Just go into the edit mode with the pencil button and use the little "x" button to clear the field, then submit the updated record.

**Comment by BDemps** [comment]
This does work, but then it still stays as an empty form (an orphan) on the
data management system. Is it okay that we'll have lots of hanging ones? I
think once I make the reassignment to "nobody" I can no longer re-assign it
to "somebody"

On Wed, Nov 29, 2017 at 2:16 PM, Karl Czajkowski <notifications@github.com>
wrote:

> I think you should be able to edit the Image Region records and clear the
> assignee entry already. Have you tried that? Just go into the edit mode
> with the pencil button and use the little "x" button to clear the field,
> then submit the updated record.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_55-23issuecomment-2D348015241&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=X63bgoBVqCM6Stg6nBMEX01J_9Bq41Z863y7pLa1nBE&s=0WpPFpdIqqX6QqcKqwh_ZrVsvvmzB1HwcWXyTkd77FQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt5rI9pvFst4ZCFXcLJyjvYT6yaC-5Fks5s7dfGgaJpZM4QlGM-2D&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=X63bgoBVqCM6Stg6nBMEX01J_9Bq41Z863y7pLa1nBE&s=K52_aIwSh-tXwQ7TLZA8bv1Zu-qAAmyc6E3Z1-nHvJM&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by BDemps** [comment]
Oops, nevermind I am very wrong. I can reassign it to "somebody" whenever I
want.

Is there a way we can add a search column for "nobody" under the
"classifiers" tab, so that I can look for things that haven't been assigned
so that I can assign these orphan ones with higher priority in the future?

On Wed, Nov 29, 2017 at 2:59 PM, William Dempsey <wdempsey@usc.edu> wrote:

> This does work, but then it still stays as an empty form (an orphan) on
> the data management system. Is it okay that we'll have lots of hanging
> ones? I think once I make the reassignment to "nobody" I can no longer
> re-assign it to "somebody"
>
> On Wed, Nov 29, 2017 at 2:16 PM, Karl Czajkowski <notifications@github.com
> > wrote:
>
>> I think you should be able to edit the Image Region records and clear the
>> assignee entry already. Have you tried that? Just go into the edit mode
>> with the pencil button and use the little "x" button to clear the field,
>> then submit the updated record.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_55-23issuecomment-2D348015241&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=X63bgoBVqCM6Stg6nBMEX01J_9Bq41Z863y7pLa1nBE&s=0WpPFpdIqqX6QqcKqwh_ZrVsvvmzB1HwcWXyTkd77FQ&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt5rI9pvFst4ZCFXcLJyjvYT6yaC-5Fks5s7dfGgaJpZM4QlGM-2D&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=X63bgoBVqCM6Stg6nBMEX01J_9Bq41Z863y7pLa1nBE&s=K52_aIwSh-tXwQ7TLZA8bv1Zu-qAAmyc6E3Z1-nHvJM&e=>
>> .
>>
>
>
>
> --
> William Dempsey, Ph.D.
> Postdoctoral Scholar
> Molecular and Computational Biology
> Dana and David Dornsife College of Letters, Arts and Sciences
> University of Southern California
> wdempsey@usc.edu
> Lab #: 213-821-1818 <(213)%20821-1818>
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
Ah, I forgot that the GUI has a problem coping with this scenario of searching for a null classifier right now. 

The only workaround I can offer at the moment is being demonstrated on the synapse-dev server.  Look for the italics _No Value_ entry in the Classifier filter control on the left side-bar.  To work around the GUI problem, I had to switch this to filter on the raw user keys (which use those short abbreviations) rather than showing the full name.

**Comment by BDemps** [comment]
No Value would be great! Is it easy to add from Dev to regular? (I just
tested it and it works like expected)

**Comment by karlcz** [comment]
It's enabled on production now.  If you think that's good enough, let's close this issue...

**Comment by BDemps** [comment]
Looks good!
