### ISSUE TITLE
Invalidation trigger sets null status during save-progress action in launcher

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#59]
Summary:  It seems that the catalog update is setting null in the Status field instead of "analysis in progress" when the user clicks the "save progress" button.

As of the past week or so, synspy-launcher (for sure in the mac version but maybe in the PC version, too...) has been having an issue where if a user hits "save progress" the actual result (as far as the launcher goes) is to put the file in the "complete" section (in my curator mode, it shows them as being "processed"). This is a new issue, so I'm not sure where it came from. It is hard to tell which exact files are affected since people have gotten assigned so many and I've been bouncing back the ones that I think are affected, but likely ones affected so far are (basically, any that have been submitted or saved between 12/21/2017 and 01/02/2018):
SynImgZfZdu20171201A6A
SynImgZfZdu20171114B3A
SynImgZfDsy20171019B3A
SynImgZfDsy20171208A3A and A6A
SynImgZfZdu20171215B3A
SynImgZfZdu20171208A3A

**Comment by karlcz** [comment]
@BDemps  As I understand it, this is working for you on the Linux workstation?  Can you do a test and confirm whether this issue affects you when you use the Mac OS launcher?  

I want to isolate whether it is the Mac build or the user privilege level that makes a difference, i.e. student graders versus you with curator privileges on the server.

**Comment by karlcz** [comment]
Based on a few of these records I looked at, it seems like the "Status" field is getting set to `null` rather than `"analysis in progress"` in a request authenticated by the assigned student grader. So, I don't think it is the server-side automation causing the problematic records since that runs under a different *robot* credential.

We still need to isolate whether it happens with all launchers for all users or whether it is specific to a class of user or a particular build of the launcher.

**Comment by BDemps** [comment]
Could this have something to do with the fact that there is a new version of the synspy-launcher? None of the undergrads have this new version installed yet. If that would fix it, I'll send them the link as soon as possible

**Comment by BDemps** [comment]
Also, looks like the error also happens with the Linux version. If I do "save progress", it disappears. These are the two files I tested and it was the same for both! If you look in curator mode, you will see that they now say "processed", as though I hit the "complete", but I am certain that I hit "save progress".

SynImgZfDsy20170713B3A
SynImgZfDsy20170713B6A

**Comment by karlcz** [comment]
OK, so this seems to confirm that it's a launcher bug affecting all builds and all users.

How critical is this? For the short term, do you think you can live with the workaround of completing a whole image stack in one session and saving it with the "complete" button?

**Comment by BDemps** [comment]
I think it's pretty critical. The undergrads are still on break for the
week, and I think they are doing these in very small bites... I've had to
bounce back a few times.

Why do you think that it could have happened all of a sudden? They've been
using the same launcher for months now.

On Tue, Jan 2, 2018 at 3:07 PM, Karl Czajkowski <notifications@github.com>
wrote:

> OK, so this seems to confirm that it's a launcher bug affecting all builds
> and all users.
>
> How critical is this? For the short term, do you think you can live with
> the workaround of completing a whole image stack in one session and saving
> it with the "complete" button?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_59-23issuecomment-2D354899635&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=vyxtQsOcnb8H62OHMJlLtCwxCrXTMlTajMGWts8yh9U&s=hlCqx-Wz7jcgJkiu4vt4obCjyjWkGcOuBu3YNVGNpug&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt0wPx-2D1Lq9eC-2DrElskfge7vvqx4cks5tGra3gaJpZM4RRFhd&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=vyxtQsOcnb8H62OHMJlLtCwxCrXTMlTajMGWts8yh9U&s=_bmYzyvT3XJRTZhd2QCtpEmFr-zar_8G21YpIJOeQA0&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
Didn't we do viewer2d changes for these users recently?  To get those changes, they had to move to a newer build of the combined launcher-viewer2d for mac or windows.

But I don't think there have been server or client changes in the past couple weeks to easily explain a new bug. Is it possible it's been broken a lot longer but nobody noticed, e.g. because they usually completed a stack at once?  Maybe that explains some of the previously incomplete stacks you found which prompted you to request the "bounce back" feature...?

**Comment by BDemps** [comment]
It's definitely new. There are several people in the lab who use their own
laptops and they've definitely not done the full stacks at one time. There
may be new changes to viewer2D but they haven't updated their
synspy-launcher applications yet. It's still the older version.

On Tue, Jan 2, 2018 at 5:04 PM, Karl Czajkowski <notifications@github.com>
wrote:

> Didn't we do viewer2d changes for these users recently? To get those
> changes, they had to move to a newer build of the combined
> launcher-viewer2d for mac or windows.
>
> But I don't think there have been server or client changes in the past
> couple weeks to easily explain a new bug. Is it possible it's been broken a
> lot longer but nobody noticed, e.g. because they usually completed a stack
> at once? Maybe that explains some of the previously incomplete stacks you
> found which prompted you to request the "bounce back" feature...?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_59-23issuecomment-2D354916754&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=Bd7HqU3H2VySpRtbYXgx1Lg2HXsZAWeJi25QTi2d8WI&s=4ANx-uwHfsazw2NN8ym0657Dh_rgpXCg9Vx5iZA8yMc&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt9tMm8iaPMMryXTQNGoFloSsvcTTks5tGtIcgaJpZM4RRFhd&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=Bd7HqU3H2VySpRtbYXgx1Lg2HXsZAWeJi25QTi2d8WI&s=KOA0a642342XxFuOz64nR3eA0QKJFd1sf3iE6eo_8P8&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
Actually, @BDemps I may have found a cause for this in a server-side DB function.  I applied a small patch to try to correct that case.  Can you re-test and see if this problem still affects you with your existing launcher?

**Comment by BDemps** [comment]
Yup, it's fixed now!

On Fri, Jan 5, 2018 at 11:57 AM, Karl Czajkowski <notifications@github.com>
wrote:

> Actually, @BDemps
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bdemps&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=A7YWkhqIYZ5ScbDVzYRMvJxBeBn66T7SsuOi2UDD4Uw&s=ERKH-rRWPjJQdjDNj0bqHorrVoz54MzsRlIzvs-X5GQ&e=>
> I may have found a cause for this in a server-side DB function. I applied a
> small patch to try to correct that case. Can you re-test and see if this
> problem still affects you with your existing launcher?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_synspy_issues_59-23issuecomment-2D355650422&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=A7YWkhqIYZ5ScbDVzYRMvJxBeBn66T7SsuOi2UDD4Uw&s=UK7ahqKaSkD_QMF-d5SoHSbQbQIxAUT4RMMEQtkha7g&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt-5FsCxCwmm-5FED9BP0f1BBUlxT7Xaeks5tHn6egaJpZM4RRFhd&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=A7YWkhqIYZ5ScbDVzYRMvJxBeBn66T7SsuOi2UDD4Uw&s=z3zvtySh3xim5PuSk4ejSu2OWYjJUQYZCDTadUuM9mM&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
Thanks for the confirmation.
