### ISSUE TITLE
Missing scroll bar after creating a long list of new items - synapse data management server

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#60]
Whenever you submit many things at the same time (e.g., behavior studies, image pair studies, zebrafish subjects, etc.), the resulting list cannot be scrolled. In order to see everything, I have to zoom out. An example is attached.
<img width="819" alt="screen shot 2018-03-12 at 2 00 14 pm" src="https://user-images.githubusercontent.com/28578487/37309366-f63cfb6e-25fd-11e8-8fe3-76675b497e53.png">

**Comment by karlcz** [comment]
Issue moved to [informatics-isi-edu/chaise #1474](https://github.com/informatics-isi-edu/chaise/issues/1474) via [**ZenHub**](https://www.zenhub.com/)
