### ISSUE TITLE
HUD/overlay text viewer2d is missing for one user

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#62]
Hi, one (and only one) of our Mac users is having an issue with the synapse-viewer2d software (tested both the v20180125.2 bundle release as well as the v20170713.12 bundle release). For some reason, the overlay text that usually appears in the top left corner of an image (saying things like slice number, gain settings when "G" is pressed, threshold settings when "f" or "n" is pressed, etc.) is not showing up on her screen. 

Is this potentially a font issue or an issue with something missing on her computer? It does not seem to be a problem for other Mac users in the lab.

These are the specs of her laptop:
max OS High Sierra Version 10.13.3
Macbook air (13 inch, 2017)

**Comment by karlcz** [comment]
@mikedarcy any idea how to diagnose this further?

**Comment by BDemps** [comment]
This person left the lab, so I think it's no longer a problem for now.
