### ISSUE TITLE
Enabling viewer2d to open multiple windows on Mac

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#63]
Hi, I was wondering whether synapse-launcher (and therefore viewer2d) could be opened up in multiple windows on my Mac. Currently, if you run the launcher through a terminal in the linux workstation, you can open multiple synapse-launcher instances. Is there a way to do that on the Mac, too? It would be great to be able to see multiple images open at the same time (probably no more than 2 at a time is necessary, though).

**Comment by karlcz** [comment]
@BDemps  is this still an issue or are you now satisfied w/ running the viewer from CLI?

Have you ever tried starting the launcher more than once from the mac terminal window?
