### ISSUE TITLE
Adding new synapse pair studies to a cohort results in a nested error

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#65]
When you click on a cohort (e.g., Cohort 105T) and you want to add to the cohort, when you click "add," an error occurs, reproduced below:
![image](https://user-images.githubusercontent.com/28578487/40453184-3dd0b6cc-5e99-11e8-8e3d-47eb2b6168da.png)
After you click "OK" for that error, a second error pops up:
![image](https://user-images.githubusercontent.com/28578487/40453207-56701678-5e99-11e8-9243-ff77d65a78ec.png)
Is there a new way to add data to cohorts?

**Comment by karlcz** [comment]
This is a known Chaise bug that is being worked on.  We'll deploy the update once it has been tested...

**Comment by karlcz** [comment]
Right, it's the "add" button that is broken right now and it affects the ability
to manage the associating links between any cohort and its members...

**Comment by karlcz** [comment]
The front-end fix for this bug was applied to production, so it should be possible to manage cohort members again.
