### ISSUE TITLE
Request type of fish

### ISSUE THREAD

**Issue by aandreev0** [informatics-isi-edu/synspy#66]
Right now i don't have API access to type of experiment in cohort. That is, Bill sends me file that looks like:

```
Learners:
Dsy20160116A	-	6025		-	3 (stars)
Zdu20170516A	-	6483		-	3
Dsy20170316B	-	6493		-	4
Dsy20161202B	-	6791		-	3
Dsy20170316A	-	7949		-	4
Dsy20171019B	-	JK6		-	4
Dsy20170426A	-	R5Y		-	3*
Dsy20180404B	-	ZHT		-	4
Zdu20180404A	-	11YG		-	3
Zdu20180404B	-	11YR		-	4

Nonlearners:
Dsy20170329C	-	6479		-	4
Dsy20171019A	-	JKE		-	4
Dsy20170202A	-	7965		-	4
Dsy20170412A	-	6481		-	4
Zdu20171114B	-	JJE		-	3
Zdu20171020A	-	JJY		-	4
Zdu20171031A	-	JJP		-	3
Zdu20171121A	-	JJ6		-	4
Zdu20180403A	-	11Z0		-	3
Dsy20180404A	-	11Z8		-	3
```

I would like to be able to pull type of experiment from storage somehow using fish ID (not sure correct terminology) like "Dsy20160116A".

**Comment by carlkesselman** [comment]
That exists and I can give you code that will get this using the standard APIs.   Let’s talk next week

Sent from my iPhone

On Aug 17, 2018, at 7:04 PM, aandreev <notifications@github.com<mailto:notifications@github.com>> wrote:


Right now i don't have API access to type of experiment in cohort. That is, Bill sends me file that looks like:

Learners:
Dsy20160116A    -       6025            -       3 (stars)
Zdu20170516A    -       6483            -       3
Dsy20170316B    -       6493            -       4
Dsy20161202B    -       6791            -       3
Dsy20170316A    -       7949            -       4
Dsy20171019B    -       JK6             -       4
Dsy20170426A    -       R5Y             -       3*
Dsy20180404B    -       ZHT             -       4
Zdu20180404A    -       11YG            -       3
Zdu20180404B    -       11YR            -       4

Nonlearners:
Dsy20170329C    -       6479            -       4
Dsy20171019A    -       JKE             -       4
Dsy20170202A    -       7965            -       4
Dsy20170412A    -       6481            -       4
Zdu20171114B    -       JJE             -       3
Zdu20171020A    -       JJY             -       4
Zdu20171031A    -       JJP             -       3
Zdu20171121A    -       JJ6             -       4
Zdu20180403A    -       11Z0            -       3
Dsy20180404A    -       11Z8            -       3


I would like to be able to pull type of experiment from storage somehow using fish ID (not sure correct terminology) like "Dsy20160116A".

**Comment by karlcz** [comment]
Did you guys ever talk about the access APIs used in the jupyter notebooks?  I'm closing this with a few extra comments.  Please re-open if you still need help...

At the model level, there is a boolean column on the `Behavior` table called `Learned?` which should be set to `true` or `false` for these runs. Using filters on this, it is easy to query for a list of just learners or just non-learners.  I would expect this to remain `null` for the various control groups which experience a variant Behavior experiment (e.g. lacking CS and/or US) and those will also be associated with a different protocol.

In general, we don't directly associate a fish with a protocol.  We associate it indirectly by linking individual observations (e.g. `Image` or `Behavior` records) with protocol steps (e.g. `tpt1`, `tpt2`, or `behave`) which are themselves children of a specific protocol.  In general, I think an individual subject will only get associated with one protocol in this manner. But, the catalog model doesn't restrict this, so a messy longitudinal record could mix observations from several protocols...

Also, I don't think Bill's "stars" QA concept is captured in the catalog at present.
