### ISSUE TITLE
Specification or design doc for the data storage system

### ISSUE THREAD

**Issue by aandreev0** [informatics-isi-edu/synspy#67]
I currently have no design doc for data storage system. That makes it hard to ask proper questions, let alone design pipeline. We ideally want to be able to write single script that runs whole pipeline given few input parameters, that ultimately generates figures for paper. Right now there are many steps already, and I don't think anyone but Bill knows them and their order.
For paper we'll also need some description of the pipeline.

Thus, spec and design doc will increase bus factor, as well as server for better design of code, and ultimately fill paper's methods section

**Comment by karlcz** [comment]
I think this was resolved with an internal document.
