### ISSUE TITLE
Can you add a small search bar to synapse-launcher?

### ISSUE THREAD

**Issue by BDemps** [informatics-isi-edu/synspy#68]
In curator mode, it would be really great if there was a feature to search. Specifically, I really only care about searching for ID, Classifier, and Date. It would help me go back through and see how many sets really have multiple segmenters.

  Any chance that this is possible/easy? If not, it's not a huge deal, just a bit of a time sink.

**Comment by karlcz** [comment]
I don't think we have the resources to further customize this app right now.  if you aren't already, try using the sort controls on the column headers to simplify your search a bit...?
